### ISSUE TITLE
Problem with Discord Interaction Infrastructure

### ISSUE THREAD

**Issue by epexa** [EsteFilipe/discord-ethereum-authentication#1]
Hi! Thank you for this project!

> Check that you now have a stack called dev-discord-interaction in Cloudformation. Cross your fingers crossed_fingers and call the command /eth-auth in your Discord channel. If everything went right with the deploy, the bot should respond with a URL.

Do you have any ideas why at this stage I am not receiving any messages from the bot on discord?

**Comment by FilipeAleixo** [comment]
When you type / (forward slash) on your server, do you see the `eth-auth` command suggested?

If not, it's probably a problem with the bot authorizations or you didn't set the right server id.

**Comment by epexa** [comment]
Hello @EsteFilipe ! Thanks for the answer!

> When you type / (forward slash) on your server, do you see the `eth-auth` command suggested?

No, there is no such command in the list.

> If not, it's probably a problem with the bot authorizations or you didn't set the right server id.

I have checked `server_id` parameter several times and others too: `app_id, public_key, bot_token, channel_id, role_id` they seem to be correct.

But I'll check again.

If you know what are the ways to check these parameters, I will be grateful!

**Comment by FilipeAleixo** [comment]
Probably an issue with Discord permissions. Check the logs on Cloudwatch for the `discord-interaction` lambda, the answer will likely be there,

**Comment by epexa** [comment]
> Probably an issue with Discord permissions. Check the logs on Cloudwatch for the `discord-interaction` lambda, the answer will likely be there,

@EsteFilipe Maybe you have the ability to communicate via chat like Telegram? Not for free.
My username: @epexa
Or write your contact in any messenger.
